In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import linear_model

In [4]:
df = pd.read_csv("hogares.csv",sep=";")
df

area  dormitorios  edad  precio
0  2600          3.0    20  550000
1  3000          4.0    15  565000
2  3200          NaN    18  610000
3  3600          3.0    30  595000
4  4000          5.0     8  760000

In [6]:
import math
median_dormitorios = math.floor(df.dormitorios.median())
median_dormitorios

3

In [8]:
df.dormitorios = df.dormitorios.fillna(median_dormitorios)
df

area  dormitorios  edad  precio
0  2600          3.0    20  550000
1  3000          4.0    15  565000
2  3200          3.0    18  610000
3  3600          3.0    30  595000
4  4000          5.0     8  760000

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','dormitorios','edad']],df.precio)

LinearRegression()

In [13]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [14]:
reg.intercept_

383724.9999999998

In [15]:
reg.predict([[3000,3,40]])

array([444400.])

In [17]:
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [18]:
reg.predict([[2500,4,5]])

array([588625.])