In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import linear_model

In [4]:
df = pd.read_csv("Datos3.csv",sep=";")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

array([859554.79452055])

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [14]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [15]:
mp.coef_

array([135.78767123])

In [16]:
mp.intercept_

180616.43835616432

In [17]:
mp.predict([[5000]])

array([859554.79452055])

In [19]:
import joblib

In [20]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [23]:
mj = joblib.load('model_joblib')

In [24]:
mj.coef_

array([135.78767123])

In [25]:
mj.intercept_

180616.43835616432

In [26]:
mj.predict([[5000]])

array([859554.79452055])