In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
import matplotlib.pyplot as plt

In [8]:
from sklearn import linear_model

In [9]:
df = pd.read_csv("DatosSoft.csv",sep=";")
df

TOWN      LON      LAT  MEDV     CRIM    ZN  INDUS  CHAS    NOX  \
0        Nahant -70.9550  42.2550  24.0  0.00632  18.0   2.31     0  0.538   
1    Swampscott -70.9500  42.2875  21.6  0.02731   0.0   7.07     0  0.469   
2    Swampscott -70.9360  42.2830  34.7  0.02729   0.0   7.07     0  0.469   
3    Marblehead -70.9280  42.2930  33.4  0.03237   0.0   2.18     0  0.458   
4    Marblehead -70.9220  42.2980  36.2  0.06905   0.0   2.18     0  0.458   
..          ...      ...      ...   ...      ...   ...    ...   ...    ...   
501    Winthrop -70.9860  42.2312  22.4  0.06263   0.0  11.93     0  0.573   
502    Winthrop -70.9910  42.2275  20.6  0.04527   0.0  11.93     0  0.573   
503    Winthrop -70.9948  42.2260  23.9  0.06076   0.0  11.93     0  0.573   
504    Winthrop -70.9875  42.2240  22.0  0.10959   0.0  11.93     0  0.573   
505    Winthrop -70.9825  42.2210  19.0  0.04741   0.0  11.93     0  0.573   

        RM   AGE     DIS  RAD  TAX  PTRATIO       B  LSTAT  
0    6.575  65.2  4.0900    1  296     15.3  396.90   4.98  
1    6.421  78.9  4.9671    2  242     17.8  396.90   9.14  
2    7.185  61.1  4.9671    2  242     17.8  392.83   4.03  
3    6.998  45.8  6.0622    3  222     18.7  394.63   2.94  
4    7.147  54.2  6.0622    3  222     18.7  396.90   5.33  
..     ...   ...     ...  ...  ...      ...     ...    ...  
501  6.593  69.1  2.4786    1  273     21.0  391.99   9.67  
502  6.120  76.7  2.2875    1  273     21.0  396.90   9.08  
503  6.976  91.0  2.1675    1  273     21.0  396.90   5.64  
504  6.794  89.3  2.3889    1  273     21.0  393.45   6.48  
505  6.030  80.8  2.5050    1  273     21.0  396.90   7.88  

[506 rows x 17 columns]

In [10]:
RegMultiple = linear_model.LinearRegression()
RegMultiple.fit(df[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']],df.MEDV)

LinearRegression()

In [11]:
RegMultiple.coef_

array([-1.06200361e-01,  4.77236832e-02,  2.32523719e-02,  2.69172651e+00,
       -1.77426230e+01,  3.78939460e+00,  5.74916809e-04, -1.50179444e+00,
        3.03760645e-01, -1.27046249e-02, -9.23911777e-01,  9.22844499e-03,
       -5.30661946e-01])

In [12]:
RegMultiple.intercept_

36.371891589434824

In [13]:
RegMultiple.predict([[0.02612,15.0,6.08,0,0.320,5.000,66.1,3.0500,4,300,14.2,395.00,3.08]])

array([32.24811474])

In [14]:
5.000+-1.06200361e-01*0.02612+4.77236832e-02*15.0+2.32523719e-02*6.08+2.69172651e+00*0+-1.77426230e+01*0.320+3.78939460e+00*5.000+5.74916809e-04*66.1+-1.50179444e+00*3.0500+ 3.03760645e-01*4+-1.27046249e-02*300+-9.23911777e-01*14.2+9.22844499e-03*395.00+-5.30661946e-01*3.08

0.8762231687675794

In [15]:
import pickle

In [18]:
with open('RegMultiple_pickle','wb') as f:
    pickle.dump(RegMultiple,f)

In [19]:
with open('RegMultiple_pickle','rb') as f:
    mp = pickle.load(f)

In [20]:
mp.predict([[0.02612,15.0,6.08,0,0.320,5.000,66.1,3.0500,4,300,14.2,395.00,3.08]])

array([32.24811474])

In [21]:
import joblib

In [22]:
joblib.dump(RegMultiple,'RegMultiple_joblib')

['RegMultiple_joblib']

In [23]:
mj = joblib.load('RegMultiple_joblib')

In [24]:
mj.predict([[0.02612,15.0,6.08,0,0.320,5.000,66.1,3.0500,4,300,14.2,395.00,3.08]])

array([32.24811474])

In [25]:
mj.coef_

array([-1.06200361e-01,  4.77236832e-02,  2.32523719e-02,  2.69172651e+00,
       -1.77426230e+01,  3.78939460e+00,  5.74916809e-04, -1.50179444e+00,
        3.03760645e-01, -1.27046249e-02, -9.23911777e-01,  9.22844499e-03,
       -5.30661946e-01])

In [26]:
mj.intercept_

36.371891589434824